#!/usr/bin/env bash

selected=$(ls ~/.screenlayout | rofi -dmenu -p "screenlayout ▶" "$@")

echo $selected 

[[ -n $selected ]] || exit

bash ~/.screenlayout/$selected
feh --bg-scale ~/Pictures/Wallpapers/Wallpaper.jpg
