#!/bin/sh

selected=$(echo -e "lock\nsuspend\nshutdown\nreboot" | dmenu)

[[ -n $selected ]] || exit

case $selected in
    lock)
        slock &
        ;;
    suspend)
        slock & systemctl suspend
        ;;
    shutdown)
        systemctl poweroff
        ;;
    reboot)
        systemctl reboot
        ;;
    *)
        exit 1
esac
